inherit_from: "configs/rgbd/tum/base_config.yaml"

Results:
  use_gui: False
  eval_rendering: True

Training:
  single_thread: False
  enable_fast_mode: False
  enable_adaptive_pruning: True
  target_reduction_ratio: 0.5
